# -*- coding: utf-8 -*-
"""zomato_analysis_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198BRwaaKgOefa-xCYaINi4hdSbDWslhp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.cluster as skcl
import sklearn.preprocessing as skpp
import sklearn.ensemble as ske

df = pd.read_csv('/content/zomato dataset.csv', encoding='latin1')

df_code=pd.read_excel('/content/Country-Code.xlsx')

df=pd.merge(df,df_code,on='Country Code')
df.head()

"""# **Data Cleaning**"""

df.head()

df.tail()

df.shape

df.describe()

df.info()

df.isnull().sum()

df.dropna(subset=['Cuisines'], inplace=True)

df.duplicated().sum()

sns.boxplot(df['Votes'])

sns.boxplot(df['Average Cost for two'])

"""Remove ouliers from average cost of two"""

Q1 = df['Average Cost for two'].quantile(0.25)
Q3 = df['Average Cost for two'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR

df = df[(df['Average Cost for two'] >= lower_limit) &
        (df['Average Cost for two'] <= upper_limit)]

"""Remove outliers from Votes"""

Q1 = df['Votes'].quantile(0.25)
Q3 = df['Votes'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR

df = df[(df['Votes'] >= lower_limit) &
        (df['Votes'] <= upper_limit)]

print(df.shape)

"""# **Data Manipulation ( Feature Engineering )**"""

# Create Ratinng Colummn (converting average rating into category)
def create_rating_category(rating):
  if rating <= 2.0:
    return "Poor"
  elif rating > 2.0 and rating <= 3.0:
    return "Average"
  elif rating > 3.0 and rating <= 4.0:
    return "Good"
  else:
    return "Excellent"

df['Rating_Category'] = df['Aggregate rating'].apply(create_rating_category)

df['Average Cost'] = df['Average Cost for two']//2

# creating category for average cost
def cost_category(cost):
  if cost <= 300:
    return "Budget"
  elif cost > 300 and cost<=700 :
    return " Moderate"
  elif cost >700 and cost <=1200:
    return "High"
  else:
    return "Expensive"
df['Cost_category'] = df['Average Cost'].apply(cost_category)

df['Popularity Score'] = df['Votes']*df['Aggregate rating' ]

"""# **Visualization**

**1. Top 3 food ordering Countries**
"""

country_count = df['Country'].value_counts()
plt.pie(country_count.head(3),autopct='%0.2f%%',labels=country_count.index[:3])
plt.title('Top 3 food odering countries')
plt.show()

"""India dominates the dataset with the highest number of restaurants

Followed by the USA and the UK, indicating Zomato's primary market is India.

**2. Distribution of Rating**
"""

plt.figure(figsize=(8,5))
sns.histplot(df['Aggregate rating'], bins=50, kde=True)
plt.title("Distribution of Rating")
plt.show()

"""Most restaurants have ratings between 2.5 and 4.5

Indicating that the majority receive average to good customer feedback.

**3. Top Countries by Number of Restraunts**
"""

country_count = df['Country'].value_counts()

plt.figure(figsize=(10,6))
country_count.head(5).plot(kind='bar')
plt.xlabel("Country")
plt.ylabel("Number of Restaurants")
plt.title("Top Countries by Number of Restaurants")
plt.show()

"""**4. Top Cities**"""

city_count = df['City'].value_counts().head(10)
plt.figure(figsize=(10,6))
sns.barplot(x=city_count.values, y=city_count.index)
plt.ylabel("City Name")
plt.xlabel("Values")
plt.title("Top Cities")
plt.show()

"""**5. Top Cuisines**"""

cuisines_count = df['Cuisines'].value_counts().head(10)
plt.figure(figsize=(10,6))
sns.barplot(x= cuisines_count.values, y=cuisines_count.index)
plt.title("Top 10 Cuisines")
plt.show()

"""**6. Votes vs Rating relationship**"""

plt.figure(figsize=(8,4))
sns.regplot(
    x= 'Votes',
    y='Aggregate rating',
    data = df,
    scatter_kws={'alpha':0.3}
)
plt.show()

"""**7. Average Reciept cost in their currencies**"""

df=df[df['Average Cost']<25000]
vt=df.groupby('Country')[["Average Cost"]].mean().reset_index()

sns.barplot(data=vt,x="Average Cost",y='Country')
plt.title('Cost in their respective currencies')
plt.show()

"""**8. Top 10 cusines order in India**"""

df.groupby('Cuisines')['Country'].value_counts()
cuisines_count = df['Cuisines'].value_counts().head(10)
plt.figure(figsize=(17,6))
sns.barplot(x=cuisines_count.index, y=cuisines_count.values)
plt.title('Top 10 cusines order in India')
plt.show()

"""**9. Ratings on the zomato**"""

plt.figure(figsize=(8,6))
sns.countplot(x='Rating text', data =df)
plt.title('Ratings on the zomato')
plt.show()

"""**10. Ratings colour across the zomato**"""

plt.figure(figsize=(8,6))
sns.countplot(x = 'Rating color', data =  df)
plt.title('Ratings colour across the zomato')
plt.show()

"""**11. Most food ordered city in India**"""

india_df = df[df['Country Code'] == 1]
count_city = india_df['City'].value_counts().head(10)
plt.figure(figsize=(10,4))
sns.scatterplot(x=count_city.index , y=count_city.values)
plt.title('Most food ordered city in India')
plt.xlabel('City')
plt.ylabel('Number of Orders')
plt.show()

"""**12. Country wise average rating**"""

plt.figure(figsize=(17,6))
sns.barplot(x='Country',y='Aggregate rating' , data =df)
plt.title('Country wise average rating')
plt.show()

"""**13. Correlation Heatmap**"""

numeric_df = df[['Votes','Aggregate rating','Price range','Average Cost','Popularity Score']]

corr_matrix = numeric_df.corr()

plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix,annot=True,cmap = 'coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""# **Important Findings**

India orders the most food through Zomato followed by US and UK
"""

country_count = df['Country'].value_counts()
plt.pie(country_count.head(3),autopct='%0.2f%%',labels=country_count.index[:3])
plt.title('Top 3 food odering countries')
plt.show()

"""Average food rating is between 2.7 to 4.0"""

plt.figure(figsize=(10,6))
sns.countplot(x='Aggregate rating', data = df)
plt.title('Average food rating is between 2.7 to 4.0')
plt.show()

"""Top 10 cuisines over the zomato"""

cuisines_count = df['Cuisines'].value_counts().head(10)
plt.figure(figsize=(10,6))
sns.barplot(x= cuisines_count.values, y=cuisines_count.index)
plt.title("Top 10 Cuisines")
plt.show()

"""Top 10 food ordering cities"""

count_city = df['City'].value_counts().head(10)
plt.figure(figsize=(10,4))
sns.scatterplot(x=count_city.index , y=count_city.values)
plt.title('Most food ordered city')
plt.xlabel('City')
plt.ylabel('Number of Orders')
plt.show()

"""Average cost for 2 around the world"""

plt.figure(figsize=(10,5))
sns.barplot(x='Average Cost', y='Country', data  = df)
plt.title('Average cost around the world')
plt.show()

"""Online food ordering possible or not"""

count_online = df['Has Online delivery'].value_counts()
plt.pie(count_online,autopct='%0.2f%%',labels=count_online.index)
plt.title('Is online delivery possible or not on zomato')
plt.show()

"""Top 10 restaurants by popularity score"""

top_rest= df.sort_values('Popularity Score' ,ascending=False).head(10)
plt.figure(figsize=(16,6))
sns.barplot(x='Restaurant Name', y='Popularity Score',data = top_rest)
plt.title('Top 10 restaurant by popularity score')
plt.xticks(rotation=45)
plt.show()

""">> indian contributes a major no. in online food ordering"""

df.to_csv('zomato_analysis_project.csv',index=False)

from google.colab import files
files.download('zomato_analysis_project.csv')